### ISSUE TITLE
Something wrong in validation funciton in RNet in cntk pyhon

### ISSUE THREAD

**Issue by egg-west** [Microsoft/samples-for-ai#26]
@MintYiqingchen  I have tested this example, but an error shows:
The error is:
different minibatch layouts detected.
It happened in line:275 in train_rnet.py, which shows the prediction of begin position and the grand truth have the different lengths.

**Comment by MintYiqingchen** [comment]
Comment the validate part can be a makeshift, you still can use --test to generate output answer. For some reasons, I have to keep the latest updated code private until May. I will update code as soon as possible that time.

**Comment by egg-west** [comment]
Well, I finally comment the F1 ,EM part and make it work. Thank you for your code, I have written my own R-Net in cntk but failed to make that work.
