### ISSUE TITLE
Clicking the Create button does nothing

### ISSUE THREAD

**Issue by kzu** [Microsoft/samples-for-ai#49]
Right now, I'm clicking Create in https://styletransfers.azurewebsites.net/ and nothing happens.

Chrome: Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by linmajia** [comment]
@kzu , thank you very much for the feedback.

Do you have a camera? The demo needs a camera to take a picture and then transfers it to a stylish one.

**Comment by kzu** [comment]
I'm running it on a laptop, which yes, has a wecam.--

--
/kzu from mobile

**Comment by linmajia** [comment]
I've synced with @kzu and reported this issue to the corresponding team. They will update the web site to show instructions and clearer error messages.
